#
#Wed Apr 22 11:57:10 GMT-03:00 2026
acceptInsecureCerts=false
browserName=firefox
moz\:debuggerAddress=true
moz\:firefoxOptions={args\=[], log\={level\=error}, prefs\={devtools.chrome.enabled\=false, devtools.debugger.remote-enabled\=true, remote.active-protocols\=1}}
webSocketUrl=true
