serenity.project.name=FLUX E2E
serenity.outputDirectory=target/site/serenity
serenity.report.encoding=UTF-8
serenity.take.screenshots=FOR_FAILURES

webdriver.driver=firefox
webdriver.autodownload=true
webdriver.base.url=http://localhost:5173

serenity.restart.browser.for.each=scenario
serenity.console.colors=true
